### ISSUE TITLE
$$() return value format

### ISSUE THREAD

**Issue by janogarcia** [Doist/ICE#3]
This should be valid ICE, but it actually doesn't work:
`$addClass($$('div.class'), 'new-class');`

On the other hand, this works as expected:
`$addClass($all('div', 'class'), 'new-class');`

This is caused by $$() and $all() not using the same result format.

The **deprecated $all() method returns an array**, via the $arrayForce helper.
`return ICE.$arrayForce(parent.querySelectorAll(selector));`  
https://github.com/Doist/ICE/blob/8391b6126cb3517babe1b6fc0feed4ceafa77d44/ICE.js#L355

While the **newer $$() method returns a NodeList object**, and thus failing when that result is passed by $addClass, $setStyle and the like to the $map method.
`return document.querySelectorAll(selector);`
https://github.com/Doist/ICE/blob/8391b6126cb3517babe1b6fc0feed4ceafa77d44/ICE.js#L337

**Comment by amix** [comment]
Fixed in latest commit
