### ISSUE TITLE
$fx.scrollToPos() not working in IE11

### ISSUE THREAD

**Issue by pmpinto** [Doist/ICE#5]
Hey @amix!

I've been trying to squash some bugs of the refactored TW pages on IE11 and traced down the issue to this function from ICE, specifically [this line](https://github.com/Doist/ICE/blob/308c431adbafc94dd8dab103bfc642b80407f2d9/ICE.js#L1845).

The issue seems to be the `$body()` part.

What I'm expecting is the page to scroll the `targetSection` until it reaches the top of the viewport. This happens on Chrome/Safari/Firefox but not on IE11.

No error is thrown on IE11, nothing happens.

Here's a short snippet of how I'm using it.

```
let targetSection = $$(target.getAttribute('href'))[0];
if (targetSection) {
    let sectionPosition = $position(targetSection).y;
    $fx.scrollToPos(sectionPosition - this.measurements.topMargin);
}
```

Something I tested that worked is replacing `$body()` with `window` on that line linked above.

**Comment by amix** [comment]
Should also be fixed in `beta` of `ist_libs`.
