### ISSUE TITLE
Inconsistent cross-browser results with $getStyle()

### ISSUE THREAD

**Issue by pmpinto** [Doist/ICE#6]
Hey @amix 😊

I'm trying to get the `padding-top` property of an element and I'm getting inconsistent results on Chrome and IE11.

```css
body {
  padding-top: 6rem;
}
```

```js
console.log($getStyle($body(), 'padding-top'));
console.log(window.getComputedStyle($body()).paddingTop);
```

On Chrome/Safari/Firefox (this is the expected result (6 * 16 = 96)):
```
// 96px
// 96px
```

On IE11:
```
// 6rem
// 96px
```

**Comment by amix** [comment]
@pmpinto Fixed in the `beta` branch of the `ist_libs`.
